### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by justintclark** [justintclark/Kent-State-Connect#16]
The user profile should read from the database to display the following information: 

Account name
Date created
Functionality to change password

Possible functionality: 
Possibility to delete account? 
Possibility to create a username?

**Comment by jtwining21** [comment]
Profiles currently displays:
Your account details are below:
Username:
Email: 
Account Created on:

Allows the user to edit:
Username:
Password:
Email: 

Will look into allowing account deletion

**Comment by justintclark** [comment]
As far as I can tell, this is complete, aside from deletion of accounts.  Thus, I'm going to move it to done, because the main point is finished. 

If you wish to add further changes, feel free to open this issue up and put it back into the "in progress" column.
