### ISSUE TITLE
database structure

### ISSUE THREAD

**Issue by justintclark** [justintclark/Kent-State-Connect#3]
Simple database structure to house user accounts and forum data

**Comment by jtwining21** [comment]
added database file 
database includes four tables:
users-
user_id (primary key);
username
user_pass
user_email
user_level
user_date

categories-
cat_id (primary key) auto_increment
cat_name
cat_destription

topics-
topic_id (primary key) auto_increment
topic_subject
topic_date
topic cat (foreign key (cat_id)) delete and update cascade
topic_by (foreign key (user_id)) delete restrict update cascade

posts-
post_id (primary key) auto_increment
post_content
post_date
post_topic (foreign key (topic_id)) delete and update cascade
post_by (foreign key (user_id)) delete restrict update cascade

**Comment by jtwining21** [comment]
Users has been updated to 
remove: user_level
add: 
user_admin (boolean)
user_confirmed (boolean)
user_confirmed_on datetime
